### ISSUE TITLE
Review and push public

### ISSUE THREAD

**Issue by aaronbell** [yangheeryu/Dongle#3]
Thank you for your patience with us getting this font reviewed and ready for shipping!

Generally it looks good. I've made a number of changes, though, that I wanted to highlight for you:
- Google Fonts requires that all fonts contain a "Regular" weight. I've renamed the "Medium" to "Regular" to conform with this requirement—please let me know if that's OK with you. 

- I note that the Latin Glyphs are really out of position in relation to the font metrics. I have shifted everything down, and received permission to set the font metrics differently than the GF CJK requirements. I also had to correct a number of components that were mispositioned as a result. I think I caught everything broken, but worth checking again. 

- I noted a number of issues with diacritic positions / designs (ogonek) that I have corrected. Please let me know if anything looks wrong or you'd like to have changed. 

- corrected widths of `.full` glyphs that were inconsistently widthed

- merged into a single glyphs source (personal preference as I like to have a single source of truth for each piece of data—so this way the metadata / feature data is all centralized in one place). 

Overall, if you could give a review to the font in general to make sure that you're happy with it and, if you are, push the repro live so we can send them off to GF.

**Comment by yangheeryu** [comment]
I made this repo public.

**Comment by aaronbell** [comment]
Great! I've fixed the description. Thanks again :)
